#define INCLINATION_PROPORTIONAL_GAIN 1.0
#define INCLINATION_INTEGRAL_GAIN 1.0
#define INCLINATION_DERIVATIVE_GAIN 1.0
#define INCLINATION_DERIVATIVE_DERIVATIVE_GAIN 1.0
#define INCLINATION_INTEGRATOR_MAX_CONST 1.0
#define INCLINATION_INTEGRATOR_MIN_CONST -1.0
